// Layer 1: the engine against swetest, Swiss Ephemeris's own reference program,
// built from the same C source (scripts/build-swetest.sh) and run on the same
// pinned files. This proves the plumbing — flags, UTC → UT1, sidereal mode,
// houses, rise/set flags — not the astronomy, which is Swiss Ephemeris's.
// Regenerate with scripts/generate-fixtures.mjs; never edit the JSON by hand.
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import type { AyanamsaName, SunriseKind } from '../src/config';
import { elongation, yogaAngle } from '../src/jyotish/panchang';
import { nakshatraOf } from '../src/jyotish/nakshatra';
import { rashiOf } from '../src/jyotish/rashi';
import { periodAround } from '../src/jyotish/crossings';
import { angularGap, inputAt, makeEngine, MILLIARCSECOND, SECOND_IN_DAYS } from './helpers';
import { computeChart } from '../src/chart';

interface BodyFixture { longitude: number; speed: number }
interface PositionSet { bodies: Record<string, BodyFixture>; ascendant: number; mc: number; house1: number }
interface PositionFixture extends Record<AyanamsaName, PositionSet> { utc: string; place: string; latitude: number; longitude: number }
interface RiseFixture extends Record<SunriseKind, { rise: number | null; set: number | null }> { date: string; place: string; latitude: number; longitude: number; body: 'sun' | 'moon'; startJd: number }
interface BoundaryFixture { label: string; kind: 'moon' | 'elongation' | 'yoga' | 'rahu'; target: number; jd: number; before: number; after: number; sampleSeconds?: number }

const fixtures = JSON.parse(readFileSync(join(__dirname, 'fixtures/swetest.json'), 'utf8')) as {
  generatedWith: { swissEphemeris: string; ephemerisCommit: string };
  positions: PositionFixture[];
  rises: RiseFixture[];
  boundaries: BoundaryFixture[];
};

describe('fixtures are for the code and files under test', () => {
  it('were generated by the same Swiss Ephemeris version on the same pinned files', () => {
    const engine = makeEngine();
    expect(fixtures.generatedWith.swissEphemeris).toBe(engine.eph.sweVersion);
    expect(fixtures.generatedWith.ephemerisCommit).toBe(engine.eph.identity.commit);
  });
});

describe.each(['lahiri', 'true_citra', 'true_pushya'] as const)('positions under %s, to 0.001″ of swetest', (ayanamsa) => {
  for (const node of ['true', 'mean'] as const) {
    it(`matches every graha, the ${node} node, Ascendant and MC for 20 instants 1850–2100`, () => {
      const engine = makeEngine({ ayanamsa, node });
      for (const f of fixtures.positions) {
        const chart = computeChart(engine, inputAt(f.utc, f.latitude, f.longitude, 0, 'UTC'));
        const expected = f[ayanamsa];
        for (const planet of chart.planets) {
          const key = planet.id === 'rahu' ? `${node}Node` : planet.id;
          if (planet.id === 'ketu') continue;
          const want = expected.bodies[key]!;
          expect(angularGap(planet.longitude, want.longitude), `${f.utc} ${f.place} ${planet.id}`).toBeLessThan(MILLIARCSECOND);
          expect(Math.abs(planet.speed - want.speed), `${f.utc} ${planet.id} speed`).toBeLessThan(1e-6);
        }
        const rahu = chart.planets.find((p) => p.id === 'rahu')!;
        const ketu = chart.planets.find((p) => p.id === 'ketu')!;
        expect(angularGap(ketu.longitude, rahu.longitude + 180)).toBeLessThan(1e-9);
        expect(angularGap(chart.ascendant.longitude, expected.ascendant), `${f.utc} ${f.place} Ascendant`).toBeLessThan(MILLIARCSECOND);
        expect(angularGap(chart.midheaven.longitude, expected.mc), `${f.utc} MC`).toBeLessThan(MILLIARCSECOND);
        expect(chart.houses.house1StartLongitude).toBe(expected.house1);
      }
    });
  }
});

describe.each(['center_true', 'limb_true', 'limb_apparent'] as const)('sunrise and sunset (%s), to 1 s of swetest', (sunrise) => {
  it('matches every place and date, and finds none where swetest finds none', () => {
    const engine = makeEngine({ sunrise });
    for (const f of fixtures.rises) {
      const want = f[sunrise];
      const rise = engine.eph.riseSet(f.startJd, f.body, 'rise', f.latitude, f.longitude);
      const set = engine.eph.riseSet(f.startJd, f.body, 'set', f.latitude, f.longitude);
      if (f.place === 'tromso') {
        // Midnight sun and polar night: there is nothing to find, and nothing is invented.
        expect(rise, `${f.date} ${f.place}`).toBeNull();
        expect(set, `${f.date} ${f.place}`).toBeNull();
        continue;
      }
      if (want.rise !== null) expect(Math.abs(rise! - want.rise), `${f.date} ${f.place} ${f.body} rise`).toBeLessThan(SECOND_IN_DAYS);
      if (want.set !== null) expect(Math.abs(set! - want.set), `${f.date} ${f.place} ${f.body} set`).toBeLessThan(SECOND_IN_DAYS);
    }
  });
});

describe('boundary instants found by bisecting swetest', () => {
  const engine = makeEngine();
  const angleOf = (kind: BoundaryFixture['kind'], jd: number): number => {
    const sun = engine.eph.position(jd, 'sun').longitude;
    const moon = engine.eph.position(jd, 'moon').longitude;
    if (kind === 'moon') return moon;
    if (kind === 'elongation') return elongation(sun, moon);
    if (kind === 'yoga') return yogaAngle(sun, moon);
    return engine.eph.position(jd, 'rahu').longitude;
  };
  // The finest division each boundary belongs to: every sign and nakshatra
  // boundary of the Moon is a pada boundary (3°20′), every tithi boundary a
  // karana boundary (6°). The search must stop at THIS boundary, not a later one.
  const DIVISION_MAS: Record<string, number> = { moon: 12_000_000, elongation: 21_600_000, yoga: 48_000_000 };

  for (const b of fixtures.boundaries) {
    it(`${b.label}: labels flip at the instant, and the end-time search finds it to 1 s`, () => {
      const step = (b.sampleSeconds ?? 1) * SECOND_IN_DAYS;
      const before = angleOf(b.kind, b.jd - step);
      const after = angleOf(b.kind, b.jd + step);
      // The engine agrees with swetest on both sides …
      expect(angularGap(before, b.before)).toBeLessThan(MILLIARCSECOND * 1000);
      expect(angularGap(after, b.after)).toBeLessThan(MILLIARCSECOND * 1000);
      // … and classifies them on opposite sides of the boundary.
      if (b.kind === 'moon' || b.kind === 'rahu') {
        const [x, y] = [rashiOf(before), rashiOf(after)];
        const [n, m] = [nakshatraOf(before), nakshatraOf(after)];
        const signChanges = b.target % 30 === 0;
        if (signChanges) expect(x.signNumber).not.toBe(y.signNumber);
        expect(`${n.number}/${n.pada}`).not.toBe(`${m.number}/${m.pada}`);
      }
      if (b.kind === 'moon' && b.target === 0) {
        expect(nakshatraOf(before)).toMatchObject({ name: 'Revati', pada: 4 });
        expect(nakshatraOf(after)).toMatchObject({ name: 'Ashwini', pada: 1 });
      }
      if (b.kind === 'rahu') {
        expect(rashiOf(before).sign).toBe('Aries');
        expect(rashiOf(after).sign).toBe('Pisces');
        return; // not a panchang limb: no end-time search
      }
      // The event search, started an hour before, lands on the same instant.
      const period = periodAround((jd) => angleOf(b.kind, jd), b.jd - 1 / 24, DIVISION_MAS[b.kind]!);
      expect(Math.abs(period.endJd - b.jd), `${b.label} end`).toBeLessThan(SECOND_IN_DAYS);
    });
  }
});
